version: "3"
services:
  srv-1:
    build:
      context: ./srv-1
      dockerfile: Dockerfile
    image: istio-srv1
    ports:
      - "5000"
    environment: 
      - NEXT_SERVICE=srv-2
      - NEXT_SERVICE_PORT=5001
    networks: 
      - main
  srv-2:
    build:
      context: ./srv-2
      dockerfile: Dockerfile
    image: istio-srv2
    ports:
      - "5001"
    environment: 
      - NEXT_SERVICE=srv-3
      - NEXT_SERVICE_PORT=5002
    networks: 
      - main
    depends_on: 
      - srv-1
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: istio-db
    ports:
      - "3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - main
  srv-3:
    build:
      context: ./srv-3
      dockerfile: Dockerfile
    image: istio-srv3
    ports:
      - "5002"
    environment: 
      - DATABASEHOST=db
      - DATABASEUSER=root
      - DATABASEPASS=123456
      - DATABASENAME=data
      - DATABASEPORT=3306
    networks: 
      - main
    depends_on: 
      - srv-2
      - db
  srv-4:
    build:
      context: ./srv-4
      dockerfile: Dockerfile
    image: istio-srv4
    ports:
      - "5003"
    environment: 
      - NEXT_SERVICE=jsonplaceholder.typicode.com
      - NEXT_SERVICE_PORT=443
      - NEXT_SERVICE_ROUTE=/users/1
    networks: 
      - main
    depends_on: 
      - srv-3
networks: 
  main: