apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: database
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: istio-db
        image: requena/istio-db:1.0
        ports:
          - containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: "123456"
